name: macOS

on:
  push:
    branches:
      - develop
      - main

env:
  SLACK_CHANNEL: ${{ secrets.SLACK_CHANNEL }}
  SLACK_SIGNING_SECRET: ${{ secrets.SLACK_SIGNING_SECRET }}
  SLACK_TOKEN: ${{ secrets.SLACK_TOKEN }}

jobs:
  build:
    runs-on: macos-12
    steps:
      - name: Check out
        uses: actions/checkout@v3
      - name: Send Slack notification
        uses: codedsolar/slack-action@v1
        if: ${{ github.event_name != 'pull_request' }}
        id: slack
        with:
          status: in-progress
      - name: Install ImageMagick
        run: brew install imagemagick
      - name: Build and install ktools
        run: ./configure && make && make install
      - name: Run ktech
        run: ktech --version
      - name: Run krane
        run: krane --version
      - name: Test
        run: ./test/test.sh
      - name: Upload test output
        uses: actions/upload-artifact@v3
        with:
          name: macos-test-output
          path: test/output/
      - name: Update Slack notification
        uses: codedsolar/slack-action@v1
        if: ${{ github.event_name != 'pull_request' && always() }}
        with:
          status: ${{ job.status }}
          timestamp: ${{ steps.slack.outputs.slack-timestamp }}
